task 01-avatar complited
js-tasks-ru/htmlcss-20230411_kirill291 pull request #10
Opened 2023-04-12 20:24 UTC by juzeppejostko

Герман, добрый вечер!

Настоящим сообщением направляю Вам первое задание четвертой лекции.

С уважением,
Кирилл

2023-04-19 11:50 UTC, juzeppejostko commented
Герман,

Я обновил ссылки на цвета в css, добавлены ссылки на переменные цветов из assets/css/main.css.

С уважением,
Кирилл

2023-05-20 11:23 UTC, juzeppejostko commented
Герман, я обновил решение.
Пожалуйста посмотри его.

2023-05-28 11:10 UTC, juzeppejostko commented
Герман, я обновил решение.

2023-05-28 20:45 UTC, GSemikozov requested changes

2023-05-28 20:45 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +    <div class="card">
компонент - avatar, не card.
все удаляем, оставляем только 2 элемента - div.avatar + img.avatar__img

2023-05-29 16:53 UTC, juzeppejostko commented on 06-lection4/01-avatar/index.html
> +    <div class="card">
Поправил

2023-05-29 16:54 UTC, juzeppejostko commented
Герман, я поправил решение

2023-05-30 12:02 UTC, GSemikozov approved these changes

2023-05-30 12:02 UTC, merged