Lecture 5 / Task 3: toggler
js-tasks-ru/htmlcss-20230411_kirill291 pull request #19
Opened 2023-06-02 08:29 UTC by juzeppejostko

Герман, направляю решение третьего задания
Все работает, осталось только заменить везде checkbox на toggle.

2023-06-02 08:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-02 08:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-02 08:40 UTC, juzeppejostko commented
Герман, поскольку в тексте задачи явно указано, что toggler и checkbox отличаются только иконками (суть одна и та же), то я взял за основу преподавательское решение задачи checkbox, заменив иконку и переименовав классы.

2023-06-02 12:57 UTC, GSemikozov requested changes

2023-06-02 12:57 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
inline-block + position: relative

2023-06-02 12:57 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
а что плох тот вариант который использовали для чекбокса?) чтобы не писать много кода)

2023-06-03 08:58 UTC, juzeppejostko commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
Поправил, но теперь элементы выстроились друг за другом в строку.
А я хотел, чтобы они, как в образце аккуратно шли друг под другом в колонку.

2023-06-03 09:00 UTC, juzeppejostko commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
Я посчитал, что если решение заменяется в репозитории на решение преподавателя, значит нужно ориентироваться на это решение, как на образец.

2023-06-03 09:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-03 09:03 UTC, juzeppejostko commented
Герман, все поправил.
Посмотри пожалуйста.

2023-06-03 10:17 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
для это в файле это можно реализовать в `07-lection5/03-toggler/index.css`

2023-06-03 10:19 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
у нас для двух подобных типов стилизованных инпутов используется один способ сокрытия нативного инпута, ему и надо следовать, чтобы кодовая база была однообразная и предсказуемая

2023-06-03 10:36 UTC, juzeppejostko commented on 07-lection5/03-toggler/toggler.css
> +    display: block;
Поправил

2023-06-03 10:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-06 20:35 UTC, GSemikozov approved these changes

2023-06-06 20:35 UTC, merged