The first task of third lecture is  completed
js-tasks-ru/htmlcss-20230411_kirill291 pull request #7
Opened 2023-04-11 19:46 UTC by juzeppejostko

Герман, добрый вечер!

Направляю решение первого задания третьей лекции.

С уважением,
Кирилл

2023-04-19 11:28 UTC, juzeppejostko commented
Герман,

Я обновил присвоение цветов, теперь они заданы не в явном виде, а через переменные в assets/css/main.css

С уважением,
Кирилл

2023-05-24 15:56 UTC, GSemikozov requested changes

2023-05-24 15:56 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.helper{
блок называется .tooltip, не может быть такого чтобы в файле стилей компонента мы описывали не один этот компонент, а сразу несколько побочных)
в общем, это хелпер надо удалить, и иконка - это часть тултипа а не хелпера.

2023-05-24 15:56 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.helper{
и не использовать селекторы тегов

2023-05-24 19:58 UTC, juzeppejostko commented on 05-lection3/01-tooltip/tooltip.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap');
поправил

2023-05-24 20:01 UTC, juzeppejostko commented on 05-lection3/01-tooltip/tooltip.css
> +.helper{
переписал полностью, пользуяюсь этой статьей: https://www.w3schools.com/css/css_tooltip.asp

2023-05-24 20:01 UTC, juzeppejostko commented
Герман, я переписал css.

2023-05-24 23:01 UTC, GSemikozov requested changes

2023-05-24 23:01 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
не хватает display: inline-block

2023-05-25 07:33 UTC, juzeppejostko commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
Поправил, если я правильно понял, то мы добавляем это свойство для того, чтобы элемент можно было после "без проблем" добавить на страницу и он "вписался".

2023-05-25 09:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
скорее для того, чтобы пользователь не наводил на блочный элемент в том месте где нет иконки и тултип не показывался

2023-05-25 09:47 UTC, GSemikozov approved these changes

2023-05-25 09:47 UTC, merged