The second task of third lecture is solved (modal)
js-tasks-ru/htmlcss-20230411_kirill291 pull request #8
Opened 2023-04-11 19:50 UTC by juzeppejostko

Герман, добрый вечер!

Направляю решение второго задания третьей лекции.

С уважением,
Кирилл

2023-04-19 11:31 UTC, juzeppejostko commented
Герман,

Я обновил css и добавил ссылки в html на цвета.

С уважением,
Кирилл

2023-05-25 12:11 UTC, juzeppejostko commented
Герман, я обновил модалку.
Пожалуйста посмотри.

2023-05-25 14:43 UTC, GSemikozov requested changes

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
1. у нас уже есть такой блок
2. это не часть модалки => удалим

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.information {
весь блок позиционируем как fixed, на всю ширину и высоту вьюпорта, фон задаем через rgba чтобы не создавать отдельный элемент .information__bckg

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.information__modal {
модальное окно позиционируем абсолютом и размещаем по середине

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 84%;
ширина должна быть задана как в макете, можно через max-width и в px

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 77%;
высоту ограничивать не нужно

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: var(--white);
на уровне этого элемента надо задать паддинги

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin-top: 15.33px;
есил позиционируем абсолютом, то марджины не нужны, нам хватит top + right

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.information__cross span {
1. селекторы тегов в БЭМ не используем 
2. иконку лучше вставить из спрайта, или если такого еще нет то просто как свг

2023-05-25 14:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    font-family: 'Inter', sans-serif;;
лишняя`;`

2023-05-25 14:59 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.button {
перенес все в .button__primary, класс .button убрал.

2023-05-25 15:10 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.information {
Поправил

2023-05-25 15:18 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.information__modal {
добавил position:absolute, если я все правильно понимаю, то сейчас окно размещается посередине и нет необходимости добавлять какое-то дополнительное свойство.

2023-05-25 20:38 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    width: 84%;
Поправил

2023-05-25 20:38 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    height: 77%;
Поправил

2023-05-25 20:40 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    background: var(--white);
добавил

2023-05-25 20:41 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    margin-top: 15.33px;
Убрал

2023-05-25 20:53 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.information__cross span {
Поправил, но с размером иконки как-будто не угадал.
Не уверен, что получилось по макету.

2023-05-25 20:53 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    font-family: 'Inter', sans-serif;;
поправил

2023-05-25 21:01 UTC, juzeppejostko commented
Герман, я все поправил.
Не уверен насчет следующего фрагмента:
.information {
    margin: 35px 35px 34px 30vw;
}
Но, как сделать правильно не понимаю, блок постоянно стремится влево.

2023-05-26 22:11 UTC, GSemikozov requested changes

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button__primary {
повторюсь - кнопка это не часть модалки и такой компонент у нас уже есть, поэтому строки 1-20 надо удалить из этого файла)

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 60vw;
а почему 60? мы должны растягивать на всю ширину вьюпорта

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 35px 35px 34px;
и марджины при этом лишние

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
через rgba (hex -> rgba)

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
если выравнивание по середине происходит через родителя, то не нужен position: absolute;

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
можно position: relative

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.information__cross span:last-child {
ранее писал что вставим свг иконку, а ненужный код - удалим. Если бы вдруг оставляли - то селекторы тегов в БЭМ не используем

2023-05-26 22:11 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.information__modal .information__text {
просто .information__text

2023-05-26 22:13 UTC, GSemikozov requested changes
и еще конфликт

2023-05-27 19:39 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.button__primary {
Убрал, но пришлось отредактировать button.css,  иначе кнопка смотрелась неаккуратно.

2023-05-27 19:39 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    width: 60vw;
Поправил, но пришлось удалить position:fixed, иначе область заполняла весь экран, перекрывая кнопку.

2023-05-27 19:44 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    margin: 35px 35px 34px;
заменил на margin-left, чтобы сохранить раастояние между кнопкой и блоком information

2023-05-27 19:46 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Поправил

2023-05-27 19:46 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
Изменил

2023-05-27 19:47 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.information__cross span:last-child {
Убрал, вставил в виде иконки через sprite.svg

2023-05-27 19:48 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.information__modal .information__text {
Поправил

2023-05-27 19:51 UTC, juzeppejostko commented
> и еще конфликт

Поправил

2023-05-28 20:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 60vw;
так именно так и должно быть)) модалка - это такой компонент, который полностью собой перекрывает контент под собой

2023-05-28 20:48 UTC, GSemikozov requested changes

2023-05-28 20:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 20px;
лишнее, оставим 48

2023-05-28 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/index.css
> +    margin: 10px;
у body марджины не нужны

2023-05-28 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin-left: 156px;
марджин удалим, добавим следующее:
`position: fixed; top: 0; left: 0;`

2023-05-28 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 81.3%;
лишнее ограничение ширины, удалим

2023-05-29 07:14 UTC, juzeppejostko commented on 03-lection1/01-button/button.css
> +    height: 20px;
Вернул назад.

2023-05-29 07:15 UTC, juzeppejostko commented on 05-lection3/02-modal/index.css
> +    margin: 10px;
убрал

2023-05-29 07:15 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    margin-left: 156px;
Поправил

2023-05-29 07:15 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +    width: 81.3%;
Убрал

2023-05-29 07:17 UTC, juzeppejostko commented
Герман, я все поправил.
Но опять модалка закрыла все окно.

2023-05-30 12:11 UTC, GSemikozov requested changes

2023-05-30 20:26 UTC, juzeppejostko commented on 05-lection3/02-modal/modal.css
> +.modal:before {
Убрал

2023-05-31 16:03 UTC, GSemikozov requested changes

2023-05-31 16:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
обязательно fixed, а не absolute

2023-05-31 19:00 UTC, juzeppejostko commented
Герман, поправил свойство 'position'.

2023-06-01 19:28 UTC, GSemikozov approved these changes

2023-06-01 19:28 UTC, merged